{
 "title": "Recommendation system",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval]) * 100",
     "legendFormat": "App"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(process_virtual_memory_bytes[$__rate_interval]) * 100",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "rate(process_resident_memory_bytes[$__rate_interval]) * 100",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "Successful Requests Increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_count{endpoint=\"/recommend\", is_valid=\"true\"}[$__rate_interval])",
     "legendFormat": "recommend"
    },
    {
     "expr": "increase(http_request_duration_seconds_count{endpoint=\"/get\", is_valid=\"true\"}[$__rate_interval])",
     "legendFormat": "events store get"
    },
    {
     "expr": "increase(http_request_duration_seconds_count{endpoint=\"/get\", is_valid=\"true\"}[$__rate_interval])",
     "legendFormat": "events store put"
    }
   ]
  },
  {
   "title": "Recommendation Request Duration Quantiles (successful)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/recommend\", is_valid=\"true\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/recommend\", is_valid=\"true\"}[$__rate_interval])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.05, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/recommend\", is_valid=\"true\"}[$__rate_interval])))",
     "legendFormat": "0.05"
    }
   ]
  },
  {
   "title": "Recommendation Request Duration Quantiles (unsuccessful)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/recommend\", is_valid=\"false\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/recommend\", is_valid=\"false\"}[$__rate_interval])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.05, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/recommend\", is_valid=\"false\"}[$__rate_interval])))",
     "legendFormat": "0.05"
    }
   ]
  },
  {
   "title": "Invalid Requests Increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "increase(invalid_request_count_total{endpoint=\"/recommend\"}[$__rate_interval])",
     "legendFormat": "recommend"
    },
    {
     "expr": "increase(invalid_request_count_total{endpoint=\"/get\"}[$__rate_interval])",
     "legendFormat": "events store get"
    },
    {
     "expr": "increase(invalid_request_count_total{endpoint=\"/put\"}[$__rate_interval])",
     "legendFormat": "events store put"
    }
   ]
  },
  {
   "title": "Events Store Get Request Duration Quantiles (successful)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/get\", is_valid=\"true\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/get\", is_valid=\"true\"}[$__rate_interval])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.05, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/get\", is_valid=\"true\"}[$__rate_interval])))",
     "legendFormat": "0.05"
    }
   ]
  },
  {
   "title": "Events Store Get Request Duration Quantiles (unsuccessful)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/get\", is_valid=\"false\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/get\", is_valid=\"false\"}[$__rate_interval])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.05, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/get\", is_valid=\"false\"}[$__rate_interval])))",
     "legendFormat": "0.05"
    }
   ]
  },
  {
   "title": "Too Many Requests Error Increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "increase(too_many_requests_count_total{endpoint=\"/recommend\"}[$__rate_interval])",
     "legendFormat": "recommend"
    },
    {
     "expr": "increase(too_many_requests_count_total{endpoint=\"/get\"}[$__rate_interval])",
     "legendFormat": "events store get"
    },
    {
     "expr": "increase(too_many_requests_count_total{endpoint=\"/put\"}[$__rate_interval])",
     "legendFormat": "events store put"
    }
   ]
  },
  {
   "title": "Events Store Put Request Duration Quantiles (successful)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/put\", is_valid=\"true\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/put\", is_valid=\"true\"}[$__rate_interval])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.05, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/put\", is_valid=\"true\"}[$__rate_interval])))",
     "legendFormat": "0.05"
    }
   ]
  },
  {
   "title": "Events Store Put Request Duration Quantiles (unsuccessful)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/put\", is_valid=\"false\"}[$__rate_interval])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/put\", is_valid=\"false\"}[$__rate_interval])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.05, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"/put\", is_valid=\"false\"}[$__rate_interval])))",
     "legendFormat": "0.05"
    }
   ]
  },
  {
   "title": "Failed Request Processing Error Increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "increase(failed_processing_count_total{endpoint=\"/recommend\"}[$__rate_interval])",
     "legendFormat": "recommend"
    },
    {
     "expr": "increase(failed_processing_count_total{endpoint=\"/get\"}[$__rate_interval])",
     "legendFormat": "events store get"
    },
    {
     "expr": "increase(failed_processing_count_total{endpoint=\"/put\"}[$__rate_interval])",
     "legendFormat": "events store put"
    }
   ]
  },
  {
   "title": "Unexpected Error Increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "increase(unexpected_error_count_total{endpoint=\"/recommend\"}[$__rate_interval])",
     "legendFormat": "recommend"
    },
    {
     "expr": "increase(unexpected_error_count_total{endpoint=\"/get\"}[$__rate_interval])",
     "legendFormat": "events store get"
    },
    {
     "expr": "increase(unexpected_error_count_total{endpoint=\"/put\"}[$__rate_interval])",
     "legendFormat": "events store put"
    }
   ]
  }
 ]
}