version: 1
disable_existing_loggers: true

formatters:
    standard:
        format: "%(asctime)s [%(name)s] [%(funcName)s] - %(levelname)s: %(message)s"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: "{{ LOG_DIR }}/info.log"
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: "{{ LOG_DIR }}/error.log"
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: "{{ LOG_DIR }}/debug.log"
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: "{{ LOG_DIR }}/critical.log"
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    warn_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: standard
        filename: "{{ LOG_DIR }}/warning.log"
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    tester_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: "{{ LOG_DIR }}/test_service.log"
        maxBytes: 10485760  # 10MB
        backupCount: 5
        encoding: utf8

root:
    level: NOTSET
    handlers: []
    propogate: no

loggers:
    recsys_service:
        level: INFO
        handlers:
            - console
            - info_file_handler
            - error_file_handler
            - critical_file_handler
            - debug_file_handler
            - warn_file_handler
        propogate: no
    recsys_service_tester:
        level: INFO
        handlers:
            # - console
            - tester_file_handler
        propogate: no